import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { 
  instancesApi, 
  messagesApi, 
  contactsApi, 
  webhooksApi, 
  apiKeysApi,
  billingApi,
  invoicesApi,
  teamApi,
  adminApi,
  broadcastsApi,
  syncApi
} from "@/lib/api";
import { toast } from "sonner";

// Query keys
export const queryKeys = {
  // WhatsApp
  instances: (params?: Record<string, unknown>) => ["instances", params] as const,
  instance: (id: string) => ["instances", id] as const,
  instanceQr: (id: string) => ["instances", id, "qr"] as const,
  instanceStatus: (id: string) => ["instances", id, "status"] as const,
  
  // Messages
  messages: (params?: Record<string, unknown>) => ["messages", params] as const,
  message: (id: string) => ["messages", id] as const,
  
  // Broadcasts
  broadcasts: (params?: Record<string, unknown>) => ["broadcasts", params] as const,
  broadcast: (id: string) => ["broadcasts", id] as const,
  broadcastRecipients: (id: string, params?: Record<string, unknown>) => ["broadcasts", id, "recipients", params] as const,
  broadcastStats: ["broadcasts", "stats"] as const,
  
  // Contacts
  contacts: (params?: Record<string, unknown>) => ["contacts", params] as const,
  contact: (id: string) => ["contacts", id] as const,
  
  // Webhooks
  webhooks: (params?: Record<string, unknown>) => ["webhooks", params] as const,
  webhook: (id: string) => ["webhooks", id] as const,
  webhookLogs: (id: string, params?: Record<string, unknown>) => ["webhooks", id, "logs", params] as const,
  
  // API Keys
  apiKeys: ["apiKeys"] as const,
  
  // Billing
  plans: ["plans"] as const,
  subscription: ["subscription"] as const,
  usage: ["usage"] as const,
  
  // Invoices
  invoices: (params?: Record<string, unknown>) => ["invoices", params] as const,
  invoice: (id: string) => ["invoices", id] as const,
  invoiceStats: ["invoiceStats"] as const,
  
  // Team
  teamMembers: ["teamMembers"] as const,
  
  // Sync
  syncStatus: (instanceId: string) => ["sync", instanceId, "status"] as const,
  
  // Admin
  adminStats: ["admin", "stats"] as const,
  adminOrganizations: (params?: Record<string, unknown>) => ["admin", "organizations", params] as const,
  adminOrganization: (id: string) => ["admin", "organizations", id] as const,
  adminUsers: (params?: Record<string, unknown>) => ["admin", "users", params] as const,
  adminInstances: (params?: Record<string, unknown>) => ["admin", "instances", params] as const,
  adminInvoices: (params?: Record<string, unknown>) => ["admin", "invoices", params] as const,
  systemHealth: ["admin", "health"] as const,
  auditLogs: (params?: Record<string, unknown>) => ["admin", "auditLogs", params] as const,
};

// ============ INSTANCES HOOKS ============

export function useInstances(params?: { page?: number; limit?: number }) {
  return useQuery({
    queryKey: queryKeys.instances(params),
    queryFn: () => instancesApi.getAll(params),
  });
}

export function useInstance(id: string) {
  return useQuery({
    queryKey: queryKeys.instance(id),
    queryFn: () => instancesApi.getById(id),
    enabled: !!id,
  });
}

export function useInstanceQr(id: string, status?: string) {
  return useQuery({
    queryKey: queryKeys.instanceQr(id),
    queryFn: () => instancesApi.getQrCode(id),
    // Only fetch QR when backend has a QR ready — prevents premature 400
    // that would poison React Query's cache and block subsequent polling
    enabled: !!id && status === 'QR_READY',
    // Poll every 5s while enabled — QR codes expire quickly and get regenerated by Baileys.
    // Using refetchInterval instead of manual useEffect+refetch() because
    // refetch() bypasses the `enabled` guard, causing 400 errors when stale
    // cached status triggers a request before revalidation completes.
    refetchInterval: status === 'QR_READY' ? 5000 : false,
    staleTime: 0,
    gcTime: 0,
    retry: 1,
    retryDelay: 2000,
  });
}

export function useInstanceStatus(id: string) {
  return useQuery({
    queryKey: queryKeys.instanceStatus(id),
    queryFn: () => instancesApi.getStatus(id),
    enabled: !!id,
    refetchInterval: 5000, // Refetch every 5 seconds
  });
}

export function useCreateInstance() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: (data: { name: string; webhook_url?: string }) => 
      instancesApi.create(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["instances"] });
      toast.success("Instance berhasil dibuat");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Gagal membuat instance");
    },
  });
}

export function useUpdateInstance() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: ({ instanceId, data }: { instanceId: string; data: Record<string, unknown> }) => 
      instancesApi.update(instanceId, data),
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ["instances"] });
      queryClient.invalidateQueries({ queryKey: queryKeys.instance(variables.instanceId) });
      toast.success("Instance berhasil diupdate");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Gagal mengupdate instance");
    },
  });
}

export function useDeleteInstance() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: (id: string) => instancesApi.delete(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["instances"] });
      toast.success("Instance berhasil dihapus");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Gagal menghapus instance");
    },
  });
}

export function useConnectInstance() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: (id: string) => instancesApi.connect(id),
    onSuccess: (_, id) => {
      queryClient.invalidateQueries({ queryKey: ["instances"] });
      queryClient.invalidateQueries({ queryKey: queryKeys.instance(id) });
      queryClient.invalidateQueries({ queryKey: queryKeys.instanceStatus(id) });
      queryClient.invalidateQueries({ queryKey: queryKeys.instanceQr(id) });
      queryClient.invalidateQueries({ queryKey: queryKeys.syncStatus(id) });
      toast.success("Menghubungkan instance...");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Gagal menghubungkan instance");
    },
  });
}

export function useDisconnectInstance() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: (id: string) => instancesApi.disconnect(id),
    onSuccess: (_, id) => {
      queryClient.invalidateQueries({ queryKey: ["instances"] });
      queryClient.invalidateQueries({ queryKey: queryKeys.instance(id) });
      queryClient.invalidateQueries({ queryKey: queryKeys.instanceStatus(id) });
      queryClient.invalidateQueries({ queryKey: queryKeys.syncStatus(id) });
      toast.success("Instance terputus");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Gagal memutuskan instance");
    },
  });
}

// ============ MESSAGES HOOKS ============

export function useMessages(params?: { 
  page?: number; 
  limit?: number; 
  instanceId?: string;
  status?: string;
  direction?: string;
  source?: string;
}) {
  return useQuery({
    queryKey: queryKeys.messages(params),
    queryFn: () => messagesApi.getAll(params),
  });
}

export function useSendMessage() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: (data: {
      instance_id: string;
      to: string;
      type: string;
      content: string | { text?: string; caption?: string; url?: string };
      media_url?: string;
    }) => messagesApi.send(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["messages"] });
      toast.success("Pesan berhasil dikirim");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Gagal mengirim pesan");
    },
  });
}

// ============ BROADCASTS HOOKS ============

export function useBroadcasts(params?: { page?: number; limit?: number; status?: string; instanceId?: string }) {
  return useQuery({
    queryKey: queryKeys.broadcasts(params),
    queryFn: () => broadcastsApi.getAll(params),
    refetchInterval: (query) => {
      const items = (query.state.data as { data?: { status: string }[] } | undefined)?.data;
      if (!items) return false;
      const hasRunning = items.some((b) => b.status === 'RUNNING');
      return hasRunning ? 3000 : false;
    },
  });
}

export function useBroadcast(id: string) {
  return useQuery({
    queryKey: queryKeys.broadcast(id),
    queryFn: () => broadcastsApi.getById(id),
    enabled: !!id,
  });
}

export function useBroadcastRecipients(id: string, params?: { page?: number; limit?: number }) {
  return useQuery({
    queryKey: queryKeys.broadcastRecipients(id, params),
    queryFn: () => broadcastsApi.getRecipients(id, params),
    enabled: !!id,
  });
}

export function useBroadcastStats() {
  return useQuery({
    queryKey: queryKeys.broadcastStats,
    queryFn: () => broadcastsApi.getStats(),
  });
}

export function useCreateBroadcast() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: (data: {
      name: string;
      instance_id: string;
      message_type: string;
      message_content: Record<string, unknown>;
      scheduled_at?: string;
    }) => broadcastsApi.create(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["broadcasts"] });
      toast.success("Broadcast berhasil dibuat");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Gagal membuat broadcast");
    },
  });
}

export function useUpdateBroadcast() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: ({ id, data }: { id: string; data: { name?: string; message_type?: string; message_content?: Record<string, unknown>; scheduled_at?: string } }) => 
      broadcastsApi.update(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["broadcasts"] });
      toast.success("Broadcast berhasil diperbarui");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Gagal memperbarui broadcast");
    },
  });
}

export function useDeleteBroadcast() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: (id: string) => broadcastsApi.delete(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["broadcasts"] });
      toast.success("Broadcast berhasil dihapus");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Gagal menghapus broadcast");
    },
  });
}

export function useStartBroadcast() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: (id: string) => broadcastsApi.start(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["broadcasts"] });
      toast.success("Broadcast dimulai");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Gagal memulai broadcast");
    },
  });
}

export function usePauseBroadcast() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: (id: string) => broadcastsApi.pause(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["broadcasts"] });
      toast.success("Broadcast dijeda");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Gagal menjeda broadcast");
    },
  });
}

export function useResumeBroadcast() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: (id: string) => broadcastsApi.resume(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["broadcasts"] });
      toast.success("Broadcast dilanjutkan");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Gagal melanjutkan broadcast");
    },
  });
}

export function useCancelBroadcast() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: (id: string) => broadcastsApi.cancel(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["broadcasts"] });
      toast.success("Broadcast dibatalkan");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Gagal membatalkan broadcast");
    },
  });
}

export function useAddBroadcastRecipients() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: ({ id, phoneNumbers }: { id: string; phoneNumbers: string[] }) => 
      broadcastsApi.addRecipients(id, { phone_numbers: phoneNumbers }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["broadcasts"] });
      toast.success("Penerima berhasil ditambahkan");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Gagal menambahkan penerima");
    },
  });
}

// ============ CONTACTS HOOKS ============

export function useContacts(params?: { page?: number; limit?: number; search?: string; instanceId?: string }) {
  return useQuery({
    queryKey: queryKeys.contacts(params),
    queryFn: () => contactsApi.getAll(params),
  });
}

export function useContact(id: string) {
  return useQuery({
    queryKey: queryKeys.contact(id),
    queryFn: () => contactsApi.getById(id),
    enabled: !!id,
  });
}

export function useCreateContact() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: (data: { 
      instance_id: string; 
      phone_number: string; 
      name?: string; 
      email?: string;
      tags?: string[] 
    }) => contactsApi.create(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["contacts"] });
      toast.success("Kontak berhasil ditambahkan");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Gagal menambahkan kontak");
    },
  });
}

export function useUpdateContact() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: ({ id, data }: { id: string; data: { phone?: string; name?: string; tags?: string[] } }) => 
      contactsApi.update(id, data),
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ["contacts"] });
      queryClient.invalidateQueries({ queryKey: queryKeys.contact(variables.id) });
      toast.success("Kontak berhasil diupdate");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Gagal mengupdate kontak");
    },
  });
}

export function useDeleteContact() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: (id: string) => contactsApi.delete(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["contacts"] });
      toast.success("Kontak berhasil dihapus");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Gagal menghapus kontak");
    },
  });
}

// ============ WEBHOOKS HOOKS ============

export function useWebhooks(params?: { page?: number; limit?: number; instanceId?: string }) {
  return useQuery({
    queryKey: queryKeys.webhooks(params),
    queryFn: () => webhooksApi.getAll(params),
  });
}

export function useWebhook(id: string) {
  return useQuery({
    queryKey: queryKeys.webhook(id),
    queryFn: () => webhooksApi.getById(id),
    enabled: !!id,
  });
}

export function useWebhookLogs(id: string, params?: { page?: number; limit?: number }) {
  return useQuery({
    queryKey: queryKeys.webhookLogs(id, params),
    queryFn: () => webhooksApi.getLogs(id, params),
    enabled: !!id,
  });
}

export function useCreateWebhook() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: (data: { instance_id: string; label: string; url: string; events: string[] }) => 
      webhooksApi.create(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["webhooks"] });
      toast.success("Webhook berhasil dibuat");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Gagal membuat webhook");
    },
  });
}

export function useUpdateWebhook() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: ({ id, data }: { id: string; data: { label?: string; url?: string; events?: string[]; is_active?: boolean } }) => 
      webhooksApi.update(id, data),
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ["webhooks"] });
      queryClient.invalidateQueries({ queryKey: queryKeys.webhook(variables.id) });
      toast.success("Webhook berhasil diupdate");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Gagal mengupdate webhook");
    },
  });
}

export function useDeleteWebhook() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: (id: string) => webhooksApi.delete(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["webhooks"] });
      toast.success("Webhook berhasil dihapus");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Gagal menghapus webhook");
    },
  });
}

export function useTestWebhook() {
  return useMutation({
    mutationFn: (id: string) => webhooksApi.test(id),
    onSuccess: () => {
      toast.success("Test webhook dikirim");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Gagal test webhook");
    },
  });
}

// ============ API KEYS HOOKS ============

export function useApiKeys() {
  return useQuery({
    queryKey: queryKeys.apiKeys,
    queryFn: () => apiKeysApi.getAll(),
  });
}

export function useCreateApiKey() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (data: { name: string; permissions: string[]; expires_at?: string }) =>
      apiKeysApi.create(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.apiKeys });
      toast.success("API key berhasil dibuat");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Gagal membuat API key");
    },
  });
}

export function useRevokeApiKey() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (id: string) => apiKeysApi.revoke(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.apiKeys });
      toast.success("API key berhasil dicabut");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Gagal mencabut API key");
    },
  });
}

// ============ BILLING HOOKS ============

export function usePlans() {
  return useQuery({
    queryKey: queryKeys.plans,
    queryFn: () => billingApi.getPlans(),
  });
}

export function useSubscription() {
  return useQuery({
    queryKey: queryKeys.subscription,
    queryFn: () => billingApi.getSubscription(),
  });
}

export function useUsage() {
  return useQuery({
    queryKey: queryKeys.usage,
    queryFn: () => billingApi.getUsage(),
  });
}

export function useSubscribe() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: (planId: string) => billingApi.subscribe(planId),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.subscription });
      queryClient.invalidateQueries({ queryKey: queryKeys.usage });
      toast.success("Berlangganan berhasil");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Gagal berlangganan");
    },
  });
}

export function useStartCheckout() {
  return useMutation({
    mutationFn: (data: { plan_id: string }) => billingApi.startCheckout(data),
    onError: (error: Error) => {
      toast.error(error.message || "Gagal memulai checkout");
    },
  });
}

export function useCancelSubscription() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: () => billingApi.cancelSubscription(),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.subscription });
      toast.success("Langganan berhasil dibatalkan");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Gagal membatalkan langganan");
    },
  });
}

// ============ INVOICES HOOKS ============

export function useInvoices(params?: { page?: number; limit?: number; status?: string }) {
  return useQuery({
    queryKey: queryKeys.invoices(params),
    queryFn: () => invoicesApi.getAll(params),
  });
}

export function useInvoice(id: string) {
  return useQuery({
    queryKey: queryKeys.invoice(id),
    queryFn: () => invoicesApi.getById(id),
    enabled: !!id,
  });
}

export function useInvoiceStats() {
  return useQuery({
    queryKey: queryKeys.invoiceStats,
    queryFn: () => invoicesApi.getStats(),
  });
}

// ============ TEAM HOOKS ============

export function useTeamMembers() {
  return useQuery({
    queryKey: queryKeys.teamMembers,
    queryFn: () => teamApi.getMembers(),
  });
}

export function useInviteMember() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: (data: { email: string; role: string }) => teamApi.inviteMember(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.teamMembers });
      toast.success("Undangan berhasil dikirim");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Gagal mengirim undangan");
    },
  });
}

export function useUpdateMember() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: ({ id, data }: { id: string; data: { role?: string; is_active?: boolean } }) =>
      teamApi.updateMember(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.teamMembers });
      toast.success("Member berhasil diupdate");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Gagal mengupdate member");
    },
  });
}

export function useRemoveMember() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: (id: string) => teamApi.removeMember(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.teamMembers });
      toast.success("Member berhasil dihapus");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Gagal menghapus member");
    },
  });
}

// ============ ADMIN HOOKS ============

export function useAdminStats() {
  return useQuery({
    queryKey: queryKeys.adminStats,
    queryFn: () => adminApi.getDashboardStats(),
  });
}

export function useAdminOrganizations(params?: { page?: number; limit?: number; status?: string }) {
  return useQuery({
    queryKey: queryKeys.adminOrganizations(params),
    queryFn: () => adminApi.getOrganizations(params),
  });
}

export function useSystemHealth() {
  return useQuery({
    queryKey: queryKeys.systemHealth,
    queryFn: () => adminApi.getSystemHealth(),
    refetchInterval: 30000, // Refetch every 30 seconds
  });
}

// ============ HISTORY SYNC HOOKS ============

export function useSyncStatus(instanceId: string) {
  return useQuery({
    queryKey: queryKeys.syncStatus(instanceId),
    queryFn: () => syncApi.getSyncStatus(instanceId),
    enabled: !!instanceId,
    staleTime: 0, // Always consider data stale — user is actively viewing this page
    refetchOnWindowFocus: 'always', // Immediately refresh when user switches back to browser tab
    refetchIntervalInBackground: true, // Keep polling even when tab is in background
    refetchInterval: (query) => {
      const data = query.state.data?.data;
      const syncStatus = data?.status;
      const instanceStatus = data?.instance_status;

      // SYNCING: poll every 2s for live progress bar
      if (syncStatus === 'SYNCING') return 2000;
      // STOPPED + connected: poll 3s (user might resume, detect changes fast)
      if (syncStatus === 'STOPPED' && instanceStatus === 'CONNECTED') return 3000;
      // STOPPED + disconnected: poll 10s (slower — just to detect reconnection)
      if (syncStatus === 'STOPPED') return 10000;
      // IDLE + connected: poll 5s (sync could start any moment after connect)
      if ((syncStatus === 'IDLE' || !syncStatus) && instanceStatus === 'CONNECTED') return 5000;
      // IDLE + connecting/QR_READY: poll 5s (about to connect → sync imminent)
      if ((syncStatus === 'IDLE' || !syncStatus) && (instanceStatus === 'CONNECTING' || instanceStatus === 'QR_READY')) return 5000;
      // COMPLETED/PARTIAL/FAILED: no polling (terminal states, only re-pair changes them)
      // IDLE + disconnected: no polling (nothing will change until reconnect)
      return false;
    },
  });
}

export function useUpdateSyncSettings() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({ instanceId, data }: { instanceId: string; data: { sync_history_on_connect?: boolean } }) =>
      syncApi.updateSyncSettings(instanceId, data),
    onSuccess: (_data, variables) => {
      queryClient.invalidateQueries({ queryKey: queryKeys.syncStatus(variables.instanceId) });
      toast.success('Sync settings updated');
    },
    onError: (error: Error) => {
      toast.error(error.message || 'Failed to update sync settings');
    },
  });
}

export function useRePairForSync() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (instanceId: string) => syncApi.rePairForSync(instanceId),
    onSuccess: (_data, instanceId) => {
      queryClient.invalidateQueries({ queryKey: ["instances"] });
      queryClient.invalidateQueries({ queryKey: queryKeys.instance(instanceId) });
      queryClient.invalidateQueries({ queryKey: queryKeys.instanceStatus(instanceId) });
      queryClient.invalidateQueries({ queryKey: queryKeys.instanceQr(instanceId) });
      queryClient.invalidateQueries({ queryKey: queryKeys.syncStatus(instanceId) });
      toast.success('Instance disconnected. Scan QR code to reconnect with history sync.');
    },
    onError: (error: Error) => {
      toast.error(error.message || 'Failed to re-pair instance');
    },
  });
}

export function useClearSyncData() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (instanceId: string) => syncApi.clearSyncData(instanceId),
    onSuccess: (_data, instanceId) => {
      queryClient.invalidateQueries({ queryKey: queryKeys.syncStatus(instanceId) });
      queryClient.invalidateQueries({ queryKey: queryKeys.messages() });
      toast.success('History sync data cleared successfully.');
    },
    onError: (error: Error) => {
      toast.error(error.message || 'Failed to clear sync data');
    },
  });
}

export function useStopSync() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (instanceId: string) => syncApi.stopSync(instanceId),
    onSuccess: (_data, instanceId) => {
      queryClient.invalidateQueries({ queryKey: queryKeys.syncStatus(instanceId) });
      toast.success('History sync stopped.');
    },
    onError: (error: Error) => {
      toast.error(error.message || 'Failed to stop sync');
    },
  });
}

export function useResumeSync() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (instanceId: string) => syncApi.resumeSync(instanceId),
    onSuccess: (_data, instanceId) => {
      queryClient.invalidateQueries({ queryKey: queryKeys.syncStatus(instanceId) });
      toast.success('History sync resumed.');
    },
    onError: (error: Error) => {
      toast.error(error.message || 'Failed to resume sync');
    },
  });
}
